#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
exec python manage.py runserver 0.0.0.0:8000

#these aren't installing. if you see this, please make this run properly
pip install requests
pip install bs4
pip install selenium