# Generated by Django 4.2.6 on 2023-11-04 01:09

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='user@odu.edu', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='exit', max_length=120, verbose_name='Email'),
            preserve_default=False,
        ),
    ]