# Generated by Django 4.2.6 on 2023-12-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_professor_is_professor_student_is_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='is_professor',
            field=models.BooleanField(default=True),
        ),
    ]
