version: '3'

volumes:
  mce_django_local_postgres_data: {}
  mce_django_local_postgres_data_backups: {}

networks:
  mynet:
    driver: bridge

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mce_django_local_django
    container_name: django
    depends_on:
      - postgres
    networks:
      - mynet
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: mce_django_production_postgres
    container_name: postgres
    volumes:
      - mce_django_local_postgres_data:/var/lib/postgresql/data
      - mce_django_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - mynet
  
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: nginx
    networks:
      - mynet
    container_name: nginx
    volumes:
      - ./compose/production/nginx/default.conf:/etc/nginx/conf.d/default.conf