# Generated by Django 4.2.6 on 2023-11-22 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_student_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Course Name')),
                ('department', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('number', models.CharField(max_length=10, verbose_name='Course Number')),
                ('credits', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MCEAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MCEQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MCERecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='name', max_length=50, verbose_name='Course')),
                ('file', models.FileField(upload_to='documents/')),
                ('file_contents', models.TextField(blank=True)),
                ('NormalizedLocation', models.CharField(max_length=120, verbose_name='Normalized Location')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('session', models.CharField(max_length=25, verbose_name='Session')),
                ('offering_time', models.CharField(verbose_name=255)),
                ('delivery_type', models.CharField(max_length=25)),
                ('meeting_type', models.CharField(max_length=25)),
                ('crn', models.IntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
            ],
        ),
        migrations.CreateModel(
            name='MCEUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.mceanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.mcequestions'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField(blank=True)),
                ('Rating', models.IntegerField(blank=True)),
                ('ProfessorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
                ('SectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.section')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
