# Generated by Django 4.2.6 on 2023-11-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ProfessorID',
            new_name='professorID',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='SectionID',
            new_name='sectionID',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Semester',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='StudentID',
            new_name='studentID',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='recquestions',
            old_name='questions_text',
            new_name='questionsText',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='delivery_type',
            new_name='deliveryType',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='meeting_type',
            new_name='meetingType',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='offering_time',
            new_name='offeringTime',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='class_name',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='NormalizedLocation',
            new_name='normalizedLocation',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='OriginalLocation',
            new_name='originalLocation',
        ),
    ]
