# Generated by Django 4.2.6 on 2023-10-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('session', models.CharField(max_length=25, verbose_name='Session')),
                ('offeringTime', models.TimeField()),
                ('professor', models.CharField(max_length=120, verbose_name='Professor Name')),
                ('deliveryType', models.CharField(max_length=25)),
                ('meetingType', models.CharField(max_length=25)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.course')),
            ],
        ),
    ]
