# Generated by Django 4.2.6 on 2023-11-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reccombined',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='reccombined',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reccombined',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='class_name',
        ),
        migrations.DeleteModel(
            name='MCERecommendation',
        ),
        migrations.DeleteModel(
            name='recAnswer',
        ),
        migrations.DeleteModel(
            name='recCombined',
        ),
        migrations.DeleteModel(
            name='recquestions',
        ),
    ]
