# Generated by Django 4.2.6 on 2023-12-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='Abbreviated semester, i.e. 202410')),
                ('friendly_name', models.CharField(max_length=255, verbose_name='Readable semester, i.e. Fall 2014')),
                ('readonly', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='delivery_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='meeting_type',
            field=models.CharField(max_length=255),
        ),
    ]
