# Generated by Django 4.2.6 on 2023-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='difficulty_rating',
            field=models.IntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='openness_rating',
            field=models.IntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='workload_rating',
            field=models.IntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
    ]
