# Generated by Django 4.2.6 on 2023-12-01 23:38

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_feedback_difficulty_rating_feedback_openness_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]