# Generated by Django 4.2.6 on 2023-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionID', models.IntegerField(verbose_name='SectionID')),
                ('StudentID', models.IntegerField(verbose_name='StudentID')),
                ('Review', models.TextField(blank=True)),
                ('Rating', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionID', models.IntegerField(verbose_name='SectionID')),
                ('OrginalLocation', models.CharField(max_length=120, verbose_name='Orginal Location')),
                ('NormalizedLocation', models.CharField(max_length=120, verbose_name='Normalized Location')),
            ],
        ),
    ]
