# Generated by Django 4.2.6 on 2023-10-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_feeback_syllabus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeback',
            new_name='Feedback',
        ),
    ]
