# Generated by Django 4.2.6 on 2023-10-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('catalogue', '0004_rename_feeback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ProfessorID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='SectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.section'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AlterField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='SectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.section'),
        ),
    ]
