# Generated by Django 4.2.6 on 2023-12-02 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_semester_alter_section_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='difficulty_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Difficulty Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='openness_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Openness Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='professor_id',
            field=models.CharField(max_length=255, verbose_name='Professor Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='section_id',
            field=models.IntegerField(blank=True, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='semester',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='workload_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Workload Rating'),
        ),
    ]
