# Generated by Django 4.2.6 on 2023-11-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_department_course_credits_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='courseID',
        ),
        migrations.AddField(
            model_name='section',
            name='CRN',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
