# Generated by Django 4.2.6 on 2023-12-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_feedback_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='crn',
        ),
        migrations.RemoveField(
            model_name='section',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='section',
            name='session',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='normalized_location',
        ),
        migrations.AddField(
            model_name='section',
            name='offering_days',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='offering_time',
            field=models.CharField(max_length=255),
        ),
    ]
