# Generated by Django 4.2.6 on 2023-12-03 20:31

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_professor_is_professor_student_is_professor'),
        ('catalogue', '0006_alter_feedback_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='normalized_location',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='section_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='professor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogue.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogue.section'),
            preserve_default=False,
        ),
    ]