# Generated by Django 4.2.6 on 2023-12-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_remove_feedback_professor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='crn',
        ),
        migrations.RemoveField(
            model_name='section',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='section',
            name='session',
        ),
        migrations.AddField(
            model_name='feedback',
            name='professor_id',
            field=models.CharField(default=0, max_length=255, verbose_name='Professor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='section_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='Course Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='offering_days',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='offering_time',
            field=models.CharField(max_length=255),
        ),
    ]
