# Generated by Django 4.2.6 on 2023-12-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_remove_feedback_professor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
