# Generated by Django 4.2.6 on 2023-12-05 02:07

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_feedback_semester_remove_feedback_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='section_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogue.section'),
            preserve_default=False,
        ),
    ]