# Generated by Django 4.2.6 on 2023-12-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_remove_feedback_section_id_feedback_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_contents',
            field=models.TextField(blank=True),
        ),
    ]
